language: node_js
node_js:
- '12'
script:
- npm test
- npm run build
deploy:
  provider: heroku
  app: sample-prject-public
  api_key:
    secure: JGEITz01WV810tghSj7YZ4UzMBAwpisu3forUYHZqsVe3OCO69hfeI1YCQDWSneRuV6gZTe1L6uRy4zqnlGj286CZeq8E4TFcHruFw3F6XKNrjQFHKEU/D5dMVNpsSF87baBnbEuRh55pd4gHxqqraVMUOMa/HezpVXgRI89im0JHNq0pnXswhJ8aNTwUMhfv3jSrsL1COUMvKJEpt8F3xwaRYi4hhPs+4htDGo63AnXoBSehdAhfr90kCtErpY6i1QcFfFep2pphfGxiU6/hiUjYZKJ5o3dpF2Py7oSFZRpSk81pTZdO0eFl0RCNY8sJbqErNPM02FIWphrRbW5b6/da2o7sogi1QTSf314zwZS+YbVjuIDCILkio0oWTS1WTfWO+sasLQScE/+eqowf4OLb9TeHdQE7n7Y/CNPsTPZePZoEoG7q5KuclaDfDBxBsG7MIqvg7QZ6uHWZHtK+NQqfG2+G81AkOBsU0CVHqdO2ch8YOxHtB/yvau3Mu+esVsfkDIWgKwO798U69Z6pafZwc+OJ928qvbBNtuWS31JZjQg2kUzArDoDIHikElIA3mJWaCLY7wt7bVykp9OyDiDrEmwR86IUFOtW+wZMbFSrjxPLwwdLjpAYXHjewsdCf0/lJFu4/XGhD4WozejSS2Y/my3c1uMerRherCanBc=
